# Use a Python 3.8 base image
FROM python:3.8-alpine

# Set the working directory to /src
WORKDIR /app

# Expose web port
EXPOSE 80

# TODO: Enable when TLS is setup
# EXPOSE 443

# Set env stage
ENV APP_STAGE=prod

# Copy the contents of the current directory into the image
COPY . .

# Install required packages
RUN pip install -r requirements-web.txt

# Command to run the API
CMD ["uvicorn", "src.run_web:app", "--host", "0.0.0.0", "--port", "443"]