# Use a Python 3.8 base image
FROM python:3.8-alpine

# Set the working directory to /src
WORKDIR /app

# Set API port
EXPOSE 8000

# Set env stage
ENV APP_STAGE=dev

# Copy the contents of the current directory into the image
COPY . .

# Install required packages
RUN pip install -r requirements.txt

# Command to run the API
CMD ["uvicorn", "src.run_api:app", "--host", "0.0.0.0", "--port", "8000"]