# Use a Python 3.8 base image
FROM python:3.8-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the contents of the current directory into the image
COPY . .

# Install required packages
RUN pip install fastapi

# Command to run the web app
CMD ["python", "run_web.py"]
