openapi: 3.0.0
info:
  title: URL Shortener API
  version: 1.0.0
servers:
  - url: https://api.example.com/shorten
paths:
  /create:
    post:
      summary: Create a new short URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
                  example: https://www.example.com
      responses:
        201:
          description: Successfully created short URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  short_url:
                    type: string
                    format: uri
                    example: https://example.com/abcdef
  /{shortUrl}:
    get:
      summary: Redirect to the original URL
      parameters:
        - name: shortUrl
          in: path
          required: true
          schema:
            type: string
      responses:
        301:
          description: Redirect to the original URL
