apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-and-api-ingress
spec:
  rules:
  - http:
      paths:
      - path: /home
        pathType: Prefix
        backend:
          service:
            name: microlink-web
            port:
              name: http
      - path: /shorten_url
        pathType: Prefix
        backend:
          service:
            name: microlink-api
            port:
              name: http
      - path: /
        pathType: Prefix
        backend:
          service:
            name: microlink-api
            port:
              name: http