apiVersion: apps/v1
kind: Deployment
metadata:
  name: microlink-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microlink-web
  template:
    metadata:
      labels:
        app: microlink-web
    spec:
      containers:
      - name: microlink-web
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY_WEB/IMAGE_WEB:TAG
        ports:
        - containerPort: 80
