apiVersion: v1
kind: Service
metadata:
  name: microlink-web
spec:
  selector:
    app: microlink-web
  ports:
    - name: http
      port: 80
      targetPort: 443
    - name: https
      port: 443
      targetPort: 443
  type: LoadBalancer
