apiVersion: apps/v1
kind: Deployment
metadata:
  name: microlink-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microlink-api
  template:
    metadata:
      labels:
        app: microlink-api
    spec:
      containers:
      - name: microlink-api
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY_API/IMAGE_API:TAG
        ports:
        - containerPort: 443
