apiVersion: v1
kind: Service
metadata:
  name: microlink-api
spec:
  selector:
    app: microlink-api
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80
  type: LoadBalancer
